name: Custom RustDesk Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get
        working-directory: flutter

      - name: Build RustDesk (Windows)
        run: flutter build windows --release
        working-directory: flutter

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RustDesk-Windows
          path: flutter/build/windows/runner/Release/
